### ISSUE TITLE
Should use absolute path to volumes in dockerfile

### ISSUE THREAD

**Issue by leeahoward** [inspectit-docker/cmr#3]
I am trying to load CMR using docker-compose.  I have this in my compose file:

```
  inspectit_cmr:
    image: inspectit/cmr
    ports:
      - "8182:8182"
      - "9070:9070"
```

 when bringing up the service I get this error:

```
ERROR: for inspectit_cmr  Cannot create container for service inspectit_cmr: Invalid bind mount spec "df518654e9de9a694cb201577d04b441f0effc06d60e82657f6b1b5205dcbf4b:db:rw": Invalid volume destination path: 'db' mount path must be absolute.
ERROR: Encountered errors while bringing up the project.
```

It looks like docker expects the volumes declared in your dockerfile to be absolute paths instead of just folder names. 

```
VOLUME ["config", "db", "storage", "ci"]
```

maybe it should be 

```
VOLUME ["/CMR/config", "/CMR/db", "/CMR/storage", "/CMR/ci"]
```
